#!/usr/bin/env python3
"""
Append description and GO term from biomart to SQLite annotation database

Usage:
    append_biomart [options] <sqlite>

Options:
    -r --reference <TYPE>  : Reference genome version (grch38/grch37/grcm38/ce11) [default: grch38]
    <sqlite>            : SQLite annotation database generated by gtf2sqlite script

"""

import sys

from docopt import docopt
import sqlite3
from pybiomart import Server


def get_dataset(reference):
    CONFIG = {
        'grch38': {
            'uri': 'http://www.ensembl.org',
            'mart': 'ENSEMBL_MART_ENSEMBL',
            'dataset': 'hsapiens_gene_ensembl'
        },
        'grch37': {
            'uri': 'http://grch37.ensembl.org',
            'mart': 'ENSEMBL_MART_ENSEMBL',
            'dataset': 'hsapiens_gene_ensembl'
        },
        'grcm38': {
            'uri': 'http://www.ensembl.org',
            'mart': 'ENSEMBL_MART_ENSEMBL',
            'dataset': 'mmusculus_gene_ensembl'
        },
        'ce11': {
            'uri': 'http://www.ensembl.org',
            'mart': 'ENSEMBL_MART_ENSEMBL',
            'dataset': 'celegans_gene_ensembl'
        }}

    # NOTE: List of marts and datasets
    # _server.list_marts()
    # _mart.list_datasets()

    _server = Server(host=CONFIG[reference]['uri'])
    _mart = _server.marts[CONFIG[reference]['mart']]
    _dataset = _mart.datasets[CONFIG[reference]['dataset']]

    return _dataset


def append(conn, dataset, columns, names_to, save_to):
    df = dataset.query(attributes=columns)
    if names_to:
        df.columns = names_to

    df.to_sql(save_to, conn, if_exists='replace', index=False)


def main():
    opt = docopt(__doc__)

    dataset = get_dataset(opt['--reference'])
    conn = sqlite3.connect(opt['<sqlite>'])

    SYMBOLS = {
        'grch38': 'hgnc_symbol',
        'grch37': 'hgnc_symbol',
        'grcm38': 'mgi_symbol',
        'ce11': None
    }
    _col_symbol = SYMBOLS[opt['--reference']]

    # NOTE: List of attribute and filter
    # dataset.list_attributes().name.to_list()
    # [attr for attr in dataset.list_attributes().name.to_list() if 'go' in attr]
    # dataset.list_filters()[dataset.list_filters().name.str.contains('id')]

    append(
        conn,
        dataset,
        columns=['ensembl_gene_id', 'go_id', 'name_1006', 'namespace_1003'],
        names_to=['gene_id', 'go_id', 'go_name', 'go_domain'],
        save_to='genes_goterms'
    )

    append(
        conn,
        dataset,
        columns=['ensembl_gene_id', 'description'],
        names_to=['gene_id', 'description'],
        save_to='gene_descriptions'
    )

    try:
        append(
            conn,
            dataset,
            columns=['ensembl_gene_id', _col_symbol],
            names_to=['gene_id', 'symbol'],
            save_to='gene_symbols'
        )
    except Exception as e:
        sys.stderr.write(f"The column of symbol was not found: {e}")
        pass

    conn.close()


if __name__ == '__main__':
    main()
